//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.arenamock.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kjoreDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="personYtelse" type="{urn:no:nav:maskinelletrekk:arenaMock:v1}PersonYtelse" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kjoreDato",
    "personYtelse"
})
@XmlRootElement(name = "ArenaMockData")
public class ArenaMockData {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar kjoreDato;
    @XmlElement(required = true)
    protected List<PersonYtelse> personYtelse;

    /**
     * Gets the value of the kjoreDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKjoreDato() {
        return kjoreDato;
    }

    /**
     * Sets the value of the kjoreDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKjoreDato(XMLGregorianCalendar value) {
        this.kjoreDato = value;
    }

    /**
     * Gets the value of the personYtelse property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personYtelse property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPersonYtelse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonYtelse }
     * </p>
     * 
     * 
     * @return
     *     The value of the personYtelse property.
     */
    public List<PersonYtelse> getPersonYtelse() {
        if (personYtelse == null) {
            personYtelse = new ArrayList<>();
        }
        return this.personYtelse;
    }

}
