//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.arenamock.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MockVedtak complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MockVedtak">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vedtaksperiode" type="{urn:no:nav:maskinelletrekk:arenaMock:v1}MockPeriode"/>
 *         <element name="rettighetstype" type="{urn:no:nav:maskinelletrekk:arenaMock:v1}MockRettighetstype"/>
 *         <element name="dagsats" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MockVedtak", propOrder = {
    "vedtaksperiode",
    "rettighetstype",
    "dagsats"
})
public class MockVedtak {

    @XmlElement(required = true)
    protected MockPeriode vedtaksperiode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MockRettighetstype rettighetstype;
    protected double dagsats;

    /**
     * Gets the value of the vedtaksperiode property.
     * 
     * @return
     *     possible object is
     *     {@link MockPeriode }
     *     
     */
    public MockPeriode getVedtaksperiode() {
        return vedtaksperiode;
    }

    /**
     * Sets the value of the vedtaksperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MockPeriode }
     *     
     */
    public void setVedtaksperiode(MockPeriode value) {
        this.vedtaksperiode = value;
    }

    /**
     * Gets the value of the rettighetstype property.
     * 
     * @return
     *     possible object is
     *     {@link MockRettighetstype }
     *     
     */
    public MockRettighetstype getRettighetstype() {
        return rettighetstype;
    }

    /**
     * Sets the value of the rettighetstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MockRettighetstype }
     *     
     */
    public void setRettighetstype(MockRettighetstype value) {
        this.rettighetstype = value;
    }

    /**
     * Gets the value of the dagsats property.
     * 
     */
    public double getDagsats() {
        return dagsats;
    }

    /**
     * Sets the value of the dagsats property.
     * 
     */
    public void setDagsats(double value) {
        this.dagsats = value;
    }

}
