//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.arenamock.v1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for MockRettighetstype</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="MockRettighetstype">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AAP"/>
 *     <enumeration value="DAGO"/>
 *     <enumeration value="LONN"/>
 *     <enumeration value="PERM"/>
 *     <enumeration value="FISK"/>
 *     <enumeration value="BASI"/>
 *     <enumeration value="BTIL"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "MockRettighetstype")
@XmlEnum
public enum MockRettighetstype {

    AAP,
    DAGO,
    LONN,
    PERM,
    FISK,
    BASI,
    BTIL;

    public String value() {
        return name();
    }

    public static MockRettighetstype fromValue(String v) {
        return valueOf(v);
    }

}
