//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.arenamock.v1;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MockSak complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MockSak">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="fagsystemSakId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="tema" type="{urn:no:nav:maskinelletrekk:arenaMock:v1}MockTema"/>
 *         <element name="vedtak" type="{urn:no:nav:maskinelletrekk:arenaMock:v1}MockVedtak" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MockSak", propOrder = {
    "fagsystemSakId",
    "tema",
    "vedtak"
})
public class MockSak {

    @XmlElement(required = true)
    protected String fagsystemSakId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MockTema tema;
    @XmlElement(required = true)
    protected List<MockVedtak> vedtak;

    /**
     * Gets the value of the fagsystemSakId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFagsystemSakId() {
        return fagsystemSakId;
    }

    /**
     * Sets the value of the fagsystemSakId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFagsystemSakId(String value) {
        this.fagsystemSakId = value;
    }

    /**
     * Gets the value of the tema property.
     * 
     * @return
     *     possible object is
     *     {@link MockTema }
     *     
     */
    public MockTema getTema() {
        return tema;
    }

    /**
     * Sets the value of the tema property.
     * 
     * @param value
     *     allowed object is
     *     {@link MockTema }
     *     
     */
    public void setTema(MockTema value) {
        this.tema = value;
    }

    /**
     * Gets the value of the vedtak property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vedtak property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getVedtak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MockVedtak }
     * </p>
     * 
     * 
     * @return
     *     The value of the vedtak property.
     */
    public List<MockVedtak> getVedtak() {
        if (vedtak == null) {
            vedtak = new ArrayList<>();
        }
        return this.vedtak;
    }

}
