//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.arenamock.v1;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.maskinelletrekk.arenamock.v1 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.maskinelletrekk.arenamock.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArenaMockData }
     * 
     * @return
     *     the new instance of {@link ArenaMockData }
     */
    public ArenaMockData createArenaMockData() {
        return new ArenaMockData();
    }

    /**
     * Create an instance of {@link PersonYtelse }
     * 
     * @return
     *     the new instance of {@link PersonYtelse }
     */
    public PersonYtelse createPersonYtelse() {
        return new PersonYtelse();
    }

    /**
     * Create an instance of {@link MockSak }
     * 
     * @return
     *     the new instance of {@link MockSak }
     */
    public MockSak createMockSak() {
        return new MockSak();
    }

    /**
     * Create an instance of {@link MockVedtak }
     * 
     * @return
     *     the new instance of {@link MockVedtak }
     */
    public MockVedtak createMockVedtak() {
        return new MockVedtak();
    }

    /**
     * Create an instance of {@link MockPeriode }
     * 
     * @return
     *     the new instance of {@link MockPeriode }
     */
    public MockPeriode createMockPeriode() {
        return new MockPeriode();
    }

}
