
package no.nav.tjeneste.virksomhet.ytelsevedtak.v1;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-02-18T12:42:16.525+01:00
 * Generated source version: 4.1.0
 */

@WebFault(name = "finnYtelseVedtakListeUgyldigInput", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1")
public class FinnYtelseVedtakListeUgyldigInput extends Exception {

    private no.nav.tjeneste.virksomhet.ytelsevedtak.v1.feil.UgyldigInput faultInfo;

    public FinnYtelseVedtakListeUgyldigInput() {
        super();
    }

    public FinnYtelseVedtakListeUgyldigInput(String message) {
        super(message);
    }

    public FinnYtelseVedtakListeUgyldigInput(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FinnYtelseVedtakListeUgyldigInput(String message, no.nav.tjeneste.virksomhet.ytelsevedtak.v1.feil.UgyldigInput finnYtelseVedtakListeUgyldigInput) {
        super(message);
        this.faultInfo = finnYtelseVedtakListeUgyldigInput;
    }

    public FinnYtelseVedtakListeUgyldigInput(String message, no.nav.tjeneste.virksomhet.ytelsevedtak.v1.feil.UgyldigInput finnYtelseVedtakListeUgyldigInput, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = finnYtelseVedtakListeUgyldigInput;
    }

    public no.nav.tjeneste.virksomhet.ytelsevedtak.v1.feil.UgyldigInput getFaultInfo() {
        return this.faultInfo;
    }
}
