package no.nav.tjeneste.virksomhet.ytelsevedtak.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-02-11T11:42:15.887+01:00
 * Generated source version: 4.1.0
 *
 */
@WebServiceClient(name = "YtelseVedtak_v1",
                  wsdlLocation = "classpath:wsdl/no/nav/tjeneste/virksomhet/ytelseVedtak/v1/YtelseVedtakV1.wsdl",
                  targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1")
public class YtelseVedtakV1_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", "YtelseVedtak_v1");
    public static final QName YtelseVedtakV1Port = new QName("http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", "YtelseVedtak_v1Port");
    static {
        URL url = YtelseVedtakV1_Service.class.getClassLoader().getResource("wsdl/no/nav/tjeneste/virksomhet/ytelseVedtak/v1/YtelseVedtakV1.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(YtelseVedtakV1_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/no/nav/tjeneste/virksomhet/ytelseVedtak/v1/YtelseVedtakV1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public YtelseVedtakV1_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public YtelseVedtakV1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YtelseVedtakV1_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public YtelseVedtakV1_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public YtelseVedtakV1_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public YtelseVedtakV1_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns YtelseVedtakV1
     */
    @WebEndpoint(name = "YtelseVedtak_v1Port")
    public YtelseVedtakV1 getYtelseVedtakV1Port() {
        return super.getPort(YtelseVedtakV1Port, YtelseVedtakV1.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YtelseVedtakV1
     */
    @WebEndpoint(name = "YtelseVedtak_v1Port")
    public YtelseVedtakV1 getYtelseVedtakV1Port(WebServiceFeature... features) {
        return super.getPort(YtelseVedtakV1Port, YtelseVedtakV1.class, features);
    }

}
