package no.nav.tjeneste.virksomhet.ytelsevedtak.v1;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-02-18T12:42:16.529+01:00
 * Generated source version: 4.1.0
 *
 */
@WebService(targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", name = "YtelseVedtak_v1")
@XmlSeeAlso({no.nav.tjeneste.virksomhet.ytelsevedtak.v1.feil.ObjectFactory.class, ObjectFactory.class, no.nav.tjeneste.virksomhet.ytelsevedtak.v1.informasjon.ObjectFactory.class, no.nav.tjeneste.virksomhet.ytelsevedtak.v1.meldinger.ObjectFactory.class})
public interface YtelseVedtakV1 {

    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1/YtelseVedtak_v1/finnYtelseVedtakListeRequest")
    @RequestWrapper(localName = "finnYtelseVedtakListe", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", className = "no.nav.tjeneste.virksomhet.ytelsevedtak.v1.FinnYtelseVedtakListe")
    @ResponseWrapper(localName = "finnYtelseVedtakListeResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", className = "no.nav.tjeneste.virksomhet.ytelsevedtak.v1.FinnYtelseVedtakListeResponse")
    @WebResult(name = "response", targetNamespace = "")
    public no.nav.tjeneste.virksomhet.ytelsevedtak.v1.meldinger.FinnYtelseVedtakListeResponse finnYtelseVedtakListe(

        @WebParam(name = "request", targetNamespace = "")
        no.nav.tjeneste.virksomhet.ytelsevedtak.v1.meldinger.FinnYtelseVedtakListeRequest request
    ) throws FinnYtelseVedtakListeSikkerhetsbegrensning, FinnYtelseVedtakListeUgyldigInput;

    @WebMethod(action = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1/YtelseVedtak_v1/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", className = "no.nav.tjeneste.virksomhet.ytelsevedtak.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://nav.no/tjeneste/virksomhet/ytelseVedtak/v1", className = "no.nav.tjeneste.virksomhet.ytelsevedtak.v1.PingResponse")
    public void ping()
;
}
