//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArenaVedtak complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ArenaVedtak">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vedtaksperiode" type="{urn:no:nav:maskinelletrekk:trekk:v1}Periode"/>
 *         <element name="tema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="rettighetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="dagsats" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArenaVedtak", propOrder = {
    "vedtaksperiode",
    "tema",
    "rettighetType",
    "dagsats"
})
public class ArenaVedtak {

    @XmlElement(required = true)
    protected Periode vedtaksperiode;
    @XmlElement(required = true)
    protected String tema;
    @XmlElement(required = true)
    protected String rettighetType;
    protected BigDecimal dagsats;

    /**
     * Gets the value of the vedtaksperiode property.
     * 
     * @return
     *     possible object is
     *     {@link Periode }
     *     
     */
    public Periode getVedtaksperiode() {
        return vedtaksperiode;
    }

    /**
     * Sets the value of the vedtaksperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periode }
     *     
     */
    public void setVedtaksperiode(Periode value) {
        this.vedtaksperiode = value;
    }

    /**
     * Gets the value of the tema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTema() {
        return tema;
    }

    /**
     * Sets the value of the tema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTema(String value) {
        this.tema = value;
    }

    /**
     * Gets the value of the rettighetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRettighetType() {
        return rettighetType;
    }

    /**
     * Sets the value of the rettighetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRettighetType(String value) {
        this.rettighetType = value;
    }

    /**
     * Gets the value of the dagsats property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDagsats() {
        return dagsats;
    }

    /**
     * Sets the value of the dagsats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDagsats(BigDecimal value) {
        this.dagsats = value;
    }

}
