//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for Beslutning</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="Beslutning">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="OS"/>
 *     <enumeration value="ABETAL"/>
 *     <enumeration value="BEGGE"/>
 *     <enumeration value="INGEN"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Beslutning")
@XmlEnum
public enum Beslutning {

    OS,
    ABETAL,
    BEGGE,
    INGEN;

    public String value() {
        return name();
    }

    public static Beslutning fromValue(String v) {
        return valueOf(v);
    }

}
