//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.maskinelletrekk.trekk.v1 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.maskinelletrekk.trekk.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Trekk }
     * 
     * @return
     *     the new instance of {@link Trekk }
     */
    public Trekk createTrekk() {
        return new Trekk();
    }

    /**
     * Create an instance of {@link TrekkRequest }
     * 
     * @return
     *     the new instance of {@link TrekkRequest }
     */
    public TrekkRequest createTrekkRequest() {
        return new TrekkRequest();
    }

    /**
     * Create an instance of {@link TrekkResponse }
     * 
     * @return
     *     the new instance of {@link TrekkResponse }
     */
    public TrekkResponse createTrekkResponse() {
        return new TrekkResponse();
    }

    /**
     * Create an instance of {@link ArenaVedtak }
     * 
     * @return
     *     the new instance of {@link ArenaVedtak }
     */
    public ArenaVedtak createArenaVedtak() {
        return new ArenaVedtak();
    }

    /**
     * Create an instance of {@link Periode }
     * 
     * @return
     *     the new instance of {@link Periode }
     */
    public Periode createPeriode() {
        return new Periode();
    }

}
