//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrekkResponse complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TrekkResponse">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="trekkvedtakId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <element name="beslutning" type="{urn:no:nav:maskinelletrekk:trekk:v1}Beslutning"/>
 *         <element name="system" type="{urn:no:nav:maskinelletrekk:trekk:v1}System" minOccurs="0"/>
 *         <element name="totalSatsOS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="totalSatsArena" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="vedtak" type="{urn:no:nav:maskinelletrekk:trekk:v1}ArenaVedtak" maxOccurs="1000" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrekkResponse", propOrder = {
    "trekkvedtakId",
    "beslutning",
    "system",
    "totalSatsOS",
    "totalSatsArena",
    "vedtak"
})
public class TrekkResponse {

    protected int trekkvedtakId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Beslutning beslutning;
    @XmlSchemaType(name = "string")
    protected System system;
    @XmlElement(required = true)
    protected BigDecimal totalSatsOS;
    @XmlElement(required = true)
    protected BigDecimal totalSatsArena;
    protected List<ArenaVedtak> vedtak;

    /**
     * Gets the value of the trekkvedtakId property.
     * 
     */
    public int getTrekkvedtakId() {
        return trekkvedtakId;
    }

    /**
     * Sets the value of the trekkvedtakId property.
     * 
     */
    public void setTrekkvedtakId(int value) {
        this.trekkvedtakId = value;
    }

    /**
     * Gets the value of the beslutning property.
     * 
     * @return
     *     possible object is
     *     {@link Beslutning }
     *     
     */
    public Beslutning getBeslutning() {
        return beslutning;
    }

    /**
     * Sets the value of the beslutning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beslutning }
     *     
     */
    public void setBeslutning(Beslutning value) {
        this.beslutning = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link System }
     *     
     */
    public System getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link System }
     *     
     */
    public void setSystem(System value) {
        this.system = value;
    }

    /**
     * Gets the value of the totalSatsOS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSatsOS() {
        return totalSatsOS;
    }

    /**
     * Sets the value of the totalSatsOS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSatsOS(BigDecimal value) {
        this.totalSatsOS = value;
    }

    /**
     * Gets the value of the totalSatsArena property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalSatsArena() {
        return totalSatsArena;
    }

    /**
     * Sets the value of the totalSatsArena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalSatsArena(BigDecimal value) {
        this.totalSatsArena = value;
    }

    /**
     * Gets the value of the vedtak property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vedtak property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getVedtak().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArenaVedtak }
     * </p>
     * 
     * 
     * @return
     *     The value of the vedtak property.
     */
    public List<ArenaVedtak> getVedtak() {
        if (vedtak == null) {
            vedtak = new ArrayList<>();
        }
        return this.vedtak;
    }

}
