//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for Trekkalternativ</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="Trekkalternativ">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="LOPD"/>
 *     <enumeration value="LOPM"/>
 *     <enumeration value="LOPP"/>
 *     <enumeration value="SALD"/>
 *     <enumeration value="SALM"/>
 *     <enumeration value="SALP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "Trekkalternativ")
@XmlEnum
public enum Trekkalternativ {

    LOPD,
    LOPM,
    LOPP,
    SALD,
    SALM,
    SALP;

    public String value() {
        return name();
    }

    public static Trekkalternativ fromValue(String v) {
        return valueOf(v);
    }

}
