//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.maskinelletrekk.trekk.v1;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="typeKjoring" type="{urn:no:nav:maskinelletrekk:trekk:v1}TypeKjoring"/>
 *         <choice>
 *           <element name="trekkRequest" type="{urn:no:nav:maskinelletrekk:trekk:v1}TrekkRequest" maxOccurs="1000"/>
 *           <element name="trekkResponse" type="{urn:no:nav:maskinelletrekk:trekk:v1}TrekkResponse" maxOccurs="1000"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeKjoring",
    "trekkRequest",
    "trekkResponse"
})
@XmlRootElement(name = "trekk")
public class Trekk {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TypeKjoring typeKjoring;
    protected List<TrekkRequest> trekkRequest;
    protected List<TrekkResponse> trekkResponse;

    /**
     * Gets the value of the typeKjoring property.
     * 
     * @return
     *     possible object is
     *     {@link TypeKjoring }
     *     
     */
    public TypeKjoring getTypeKjoring() {
        return typeKjoring;
    }

    /**
     * Sets the value of the typeKjoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeKjoring }
     *     
     */
    public void setTypeKjoring(TypeKjoring value) {
        this.typeKjoring = value;
    }

    /**
     * Gets the value of the trekkRequest property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trekkRequest property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTrekkRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrekkRequest }
     * </p>
     * 
     * 
     * @return
     *     The value of the trekkRequest property.
     */
    public List<TrekkRequest> getTrekkRequest() {
        if (trekkRequest == null) {
            trekkRequest = new ArrayList<>();
        }
        return this.trekkRequest;
    }

    /**
     * Gets the value of the trekkResponse property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trekkResponse property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTrekkResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrekkResponse }
     * </p>
     * 
     * 
     * @return
     *     The value of the trekkResponse property.
     */
    public List<TrekkResponse> getTrekkResponse() {
        if (trekkResponse == null) {
            trekkResponse = new ArrayList<>();
        }
        return this.trekkResponse;
    }

}
