//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.trygdeetaten.skjema.oppdrag;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Inneholder elementene som skal være med i en input 157-rekord, vedtakssats
 * 
 * <p>Java class for vedtakssats-157 complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="vedtakssats-157">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vedtakssats" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tsats"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vedtakssats-157", propOrder = {
    "vedtakssats"
})
public class Vedtakssats157 {

    @XmlElement(required = true)
    protected BigDecimal vedtakssats;

    /**
     * Gets the value of the vedtakssats property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVedtakssats() {
        return vedtakssats;
    }

    /**
     * Sets the value of the vedtakssats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVedtakssats(BigDecimal value) {
        this.vedtakssats = value;
    }

}
